version: '3.9'
services:
  test-mysql:
    container_name: test-mysql
    image: mysql:8.0.28-oracle
    ports:
      - '23306:3306'
    networks:
      - unit-test
    environment:
      - TZ=Asia/Singapore
      - MYSQL_DATABASE=apitable_test
      - MYSQL_USER=apitable
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command: ['mysqld', '--sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  test-redis:
    container_name: test-redis
    image: redis:5.0.7-alpine
    ports:
      - '26379:6379'
    networks:
      - unit-test
    environment:
      - TZ=Asia/Singapore
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  test-rabbitmq:
    container_name: test-rabbitmq
    image: rabbitmq:3-management
    ports:
      - '25672:5672'
    networks:
      - unit-test
    environment:
      - TZ=Asia/Singapore
      - RABBITMQ_USERNAME=apitable
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_DEFAULT_USER=apitable
      - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  test-mongo:
    container_name: test-mongo
    image: mongo:5.0.6
    ports:
      - '7017:27017'
    networks:
      - unit-test
    volumes:
      - ./init-db/src/main/resources/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - TZ=Asia/Singapore
      - MONGO_INITDB_DATABASE=apitable_test
      - MONGO_USERNAME=apitable
      - MONGO_PASSWORD=password
      - MONGO_INITDB_ROOT_USERNAME=apitable
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  test-initdb:
    container_name: test-initdb
    image: ${INITDB_IMAGE:-docker.vika.ltd/vikadata/vika/init-db:latest-alpha}
    networks:
      - unit-test
    environment:
      - TZ=Asia/Singapore
      - ACTION=update
      - DB_HOST=test-mysql
      - DB_PORT=3306
      - DB_NAME=apitable_test
      - DB_USERNAME=apitable
      - DB_PASSWORD=password

  unit-test-room:
    container_name: unit-test-room
    networks:
      - unit-test
    build:
      context: .
      dockerfile: packaging/Dockerfile.room-server
      target: builder
    volumes:
      - ./packages/room-server/coverage:/tmp/vikadata/packages/room-server/coverage
    environment:
      - TZ=Asia/Singapore
      - MYSQL_HOST=test-mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=apitable
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=apitable_test
      - MYSQL_USE_SSL=false
      - REDIS_HOST=test-redis
      - REDIS_PORT=6379
      - REDIS_DB=4
      - REDIS_PASSWORD=
      - RABBITMQ_HOST=test-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=apitable
      - RABBITMQ_PASSWORD=password
      - INSTANCE_COUNT=1
      - APPLICATION_NAME=NEST_REST_SERVER
    # remove default command，use run unit-test-room (yarn test:ut:room:cov | yarn test:ut:room)

  unit-test-backend:
    container_name: unit-test-backend
    image: amazoncorretto:8
    working_dir: /app
    networks:
      - unit-test
    volumes:
      - ./backend-server:/app
    environment:
      - JVM_OPTS="-Xms3200m -Xmx3200m"
      - MYSQL_HOST=test-mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=apitable
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=apitable_test
      - REDIS_HOST=test-redis
      - REDIS_PORT=6379
      - REDIS_DB=3
      - REDIS_PASSWORD=
      - RABBITMQ_HOST=test-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=apitable
      - RABBITMQ_PASSWORD=password
      - MONGO_HOST=test-mongo:27017
      - MONGO_USERNAME=apitable
      - MONGO_PASSWORD=password
      - MONGO_DATABASE=apitable_test
    entrypoint: ./gradlew testCodeCoverageReport --stacktrace

networks:
  unit-test:
    driver: bridge
