services:

  backend-server:
    image: amazoncorretto:8
    restart: always
    ports:
      - 8081:8081
    expose:
      - "8081"
    working_dir: /devenv
    volumes:
      - ./backend-server:/devenv
    environment:
      - HOME=/devenv
    networks:
      - apitable
    command: sh -c "./gradlew build -x test && java -jar vikadata-service/vikadata-service-api/build/libs/vikadata-service-api.jar"

  web-server:
    image: node:16.15.0-alpine
    restart: always
    ports:
      - 3000:3000
    expose:
      - "3000"
    working_dir: /devenv
    volumes:
      - ./:/devenv
    environment:
      - HOME=/devenv
    networks:
      - apitable
    command: sh -c "yarn install && yarn build:dst:pre && yarn sd:r"

  room-server:
    image: node:16.15.0-alpine
    restart: always
    ports:
     - 3333:3333
     - 3334:3334
    expose:
      - "3333"
      - "3334"
    working_dir: /devenv
    volumes:
      - ./:/devenv
    environment:
      - HOME=/devenv
    networks:
      - apitable
    command: sh -c "yarn install && yarn start:room-server"
  socket-server:
    image: node:16.15.0-alpine
    restart: always
    ports:
      - 3001:3001
      - 3002:3002
      - 3005:3005
      - 3007:3007
    expose:
      - "3001"
      - "3002"
      - "3005"
      - "3007"
    working_dir: /devenv
    volumes:
      - ./:/devenv
    environment:
      - HOME=/devenv
    networks:
      - apitable
    command: sh -c "cd packages/socket-server/ && yarn && yarn run start:dev"
networks:
  apitable:
    driver: bridge