services:
  backend-server:
    image: amazoncorretto:8
    restart: always
    working_dir: /app
    environment:
      - HOME=/app
    volumes:
      - ${PWD}/backend-server:/app
  web-server:
    image: ghcr.io/vikadata/vika/nodepy
    restart: always
    working_dir: /app
    environment:
      - HOME=/app
    volumes:
      - ${PWD}:/app
  socket-server:
    image: ghcr.io/vikadata/vika/nodepy
    restart: always
    working_dir: /app
    environment:
      - HOME=/app
    volumes:
      - ${PWD}/packages/socket-server:/app
