additionalRepositories:
  - url: https://github.com/vikadata/db-manage
    checkoutLocation: db-manage
  - url: https://github.com/vikadata/vikadata-websocket
    checkoutLocation: vikadata-websocket

image:
  file: .gitpod.Dockerfile

tasks:
  - name: java-server
    init: |
      source scripts/install-utils.sh
      bash ./devtools.sh setup-redis
      bash ./devtools.sh setup-mysql
      bash ./devtools.sh setup-rabbitmq
      ./gradlew build -x test
    command: |
      bash ./devtools.sh setup-redis
      bash ./devtools.sh launch-service-api
    openMode: tab-before
  - name: init-users & open browser
    command: |
      gp await-port 8081
      bash ./devtools.sh init-users
      gp preview $(gp url 8081)/api/v1/doc.html
  - name: websocket-server
    before: |
      cd ../vikadata-websocket
    init: |
      yarn
    command: |
      yarn run start:dev
    openMode: tab-after
  - name: command line for free
    command: echo "Hi, Vikaer"
    openMode: tab-after
              
ports:
  # Java Server (/api/v1/doc.html)
  - port: 8081
    onOpen: ignore
  # Adminer
  - port: 8088
    onOpen: open-preview
