version: '3'
services:
  vika-redis:
    container_name: vika-redis
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379
    restart: always

  vika-adminer:
    container_name: vika-adminer
    image: adminer
    ports:
      - 8088:8080
    links:
      - "vika-mysql:db"

  vika-mysql:
    container_name: vika-mysql
    image: mysql:8.0.23
    volumes:
      - vika-mysql-data:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=vika
      - MYSQL_DATABASE=vika_dev
    restart: always
    command: ['mysqld', '--sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  vika-mysql-test:
    container_name: vika-mysql-test
    image: mysql:8.0.23
    ports:
      - 33061:3306
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=vika
      - MYSQL_DATABASE=vika_test
    command: ['mysqld', '--sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  vika-rabbit-mq:
    container_name: vika-rabbit-mq
    image: rabbitmq:3-management
    volumes:
      - vika-rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 56710:5671
      - 56720:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=vika
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_DEFAULT_USER=vika
      - RABBITMQ_DEFAULT_PASS=password
    restart: always

volumes:
  vika-mysql-data:
  vika-rabbitmq-data:
