release_docker:
  stage: docker
  image: vikadata/dind-java:latest
  services:
    - name: vikadata/dind-java:latest
      command: [ "--registry-mirror=https://nt14bg6k.mirror.aliyuncs.com" ]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://vikadata__dind-java:2375"
    BUILD_ENV: production
    VERSION_TYPE: release
    DOCKER_IMAGE_NAME: cargo.vikadata.com/vika-prod_release/backend-server
    DOCKER_IMAGE_TAG: 0.13.3-$BUILD_ENV.$VERSION_TYPE.$CI_PIPELINE_ID
  # 缓存依赖
  cache:
    # 继承全局配置
    key: $CI_PROJECT_NAME
    paths:
      - .gradle/
    policy: pull-push
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew -v
    - ./gradlew build -D profile=$BUILD_ENV --build-cache -x test
    - cp -r vikadata-service/vikadata-service-api/build/libs/vikadata-service-api.jar ./docker
    - echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> docker.env
    - echo "BUILD_ENV=$BUILD_ENV" >> docker.env
    - chmod a+x ./ci/script/build_docker.sh
    - sh ./ci/script/build_docker.sh
  artifacts:
    name: $CI_JOB_ID
    paths:
      - ci/script
    expire_in: 1 day
    reports:
      dotenv: docker.env
  only:
    refs:
      - tags
  tags:
    - backend

release_deploy:
  stage: deploy
  dependencies:
    - release_docker
  image: python:3.9.2
  variables:
    # 不需要拉取代码
    GIT_STRATEGY: none
    # 集群名称
    CLUSTER_NAME: user-21b785-20200409100351-1a0l
    # 分区
    PARTITION: production
    # 租户
    TENANT: vika-prod
    # 应用名称
    APP_NAME: backend-server
    # NAMESPACE
    NAMESPACE: production
    # 跟EKS集群上的工作负载名称一致
    DEPLOY_NAME: backend-server-v1
    # 镜像名
    DOCKER_IMAGE_NAME: cargo.vikadata.com/vika-prod_release/backend-server
  # 不需要缓存
  cache: {}
  script:
    - chmod a+x ./ci/script/deploy.sh
    - ./ci/script/deploy.sh
  only:
    refs:
      - tags
  tags:
    - backend
  when: manual

release_ks_deploy:
  stage: deploy
  dependencies:
    - release_docker
  image: python:3.9.2
  variables:
    # 不需要拉取代码
    GIT_STRATEGY: none
    # 集群名称
    CLUSTER_NAME: user-21b785-20200409100351-1a0l
    # 分区
    PARTITION: production
    # 租户
    TENANT: vika-prod
    # 应用名称
    APP_NAME: backend-server
    # NAMESPACE
    NAMESPACE: production
    # 跟EKS集群上的工作负载名称一致
    DEPLOY_NAME: backend-server-v1
    # 镜像名
    DOCKER_IMAGE_NAME: cargo.vikadata.com/vika-prod_release/backend-server
  # 不需要缓存
  cache: {}
  script:
    - DEPLOY_SERVER="$DEPLOY_SERVER_PRODUCTION"
    - EKS_SERVER=https://DD0A14D35441423ADC840071E0926891.sk1.cn-northwest-1.eks.amazonaws.com.cn
    - sh ./ci/script/deploy-eks.sh
  only:
    refs:
      - tags
  tags:
    - backend
  when: manual
