server:
  port: 9111
  shutdown: graceful

spring:
  application:
    name: scheduler-space
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:33060}/${DB_DATABASE:vika_dev}?characterEncoding=utf8&autoReconnect=true
    username: ${DB_USERNAME:vika}
    password: ${DB_PWD:password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    timeout: 30000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

config:
  resource-url: http://s1.vika.ltd
  oss-bucket-name: vk-assets-ltd
  oss-type: QNY1
  dt-censor-path: http://api.vika.ltd/imageCensor/index.html
  dt-censor-chat-id: chat8a6b4b9005eb763cc560db4b21e695ef
  v-code-statistics-datasheet: dstZcjB3zbdPuemkka

# vikadata 组件配置
vikadata-starter:
  job:
    register-address: http://job.vika.ltd
    port: 9091
    appname: space-job-executor
    address: space-job-executor:9091
    ip: 127.0.0.1
    logpath: /logs/vikadata/job/space
    logretentiondays: 7
    access-token: onJvanLmSE3CqotjNp8hb7WRolpM1pdL
  oss:
    type: qiniu
    qiniu:
      access-key: B7OyF1ZORX4iHaqJ5uN62qXAgoDnc7Jv7_zf1SpJ
      secret-key: Hp26Vj4D2bv0JQ-qgExXYKlKc5EkFuVVgW1GA1Eh
      region: z2
  social:
    dingtalk:
      enabled: true
      isv-corp-id: dingc7ad99cf1e0ad49a35c2f4657eb6378f
      suite-id: 7242002
      suite-key: suite88qw1yq0q48b4tez
      suite-secret: 6ITdgMwVcDYgnHT-IfG8_Szvc8-vMWBwwkCUjdlNaxWgGDFXQaYAsO_jhpyXdpg1
      corp-h5-app:
        app-key: dingpp0pil1snqypkjym
        app-secret: ZrVyKPrGkOeLMTmlDmFmcPK3eUIEDmABwT2DxuQONBOoTqZ0p1JEOedqxV_rNBo3
      mobile-app:
        app-id: dingoaumy4mh7oesecamid
        app-secret: A1-kYsquLtLr9e_XXnOAoMaqxEjC5xvMUeAztFxPy8YGgsYmeXsSu7QvwrmCcw1P
      vika-dst-id: dstKLuqVp99GRxHtNW
  vika:
    enabled: true
    host: https://integration.vika.ltd
    token: usk8qo1Dk9PbecBlaqFIvbb
internal:
  domain: http://backend-server:8081
  getPausedUserHistoryInfoURL: /api/v1/internal/getUserHistories
  closePausedUserURL: /api/v1/internal/users/{userId}/close
