private_aider_build:
  stage: docker
  image: vikadata/dind-java:latest
  services:
    - name: vikadata/dind-java:latest
      command: [ "--registry-mirror", "https://nt14bg6k.mirror.aliyuncs.com" ]
  variables:
    VERSION_TYPE: private
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://vikadata__dind-java:2375"
    # 不需要拉取代码
    DOCKER_IMAGE_NAME: cargo.vikadata.com/system-tenant_private/aider-server
    DOCKER_IMAGE_TAG: 0.9.2-$CI_COMMIT_REF_NAME.$VERSION_TYPE.$CI_PIPELINE_ID
  before_script:
    - ./gradlew -v
    - docker --version
    - java -version
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew build -D profile=private -x test
    - cp -r vikadata-project/private-aider-service/build/libs/private-aider-service.jar ./docker
    - docker login -u $ECR_LOGIN_NAME -p $ECR_PASSWORD $ECR_PATH
    - cd docker || exit 1
    - docker build --tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG . || exit 1
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG || exit 1
    - curl --connect-timeout 5 -m 5 -d "branch=$CI_COMMIT_REF_NAME&app=private-aider-server&image=$DOCKER_IMAGE_TAG" http://jenkins.vika.ltd:8080/job/patch_app/buildWithParameters?token=tg-build-only || exit 1
    # 缓存依赖
  cache:
    # 继承全局配置
    key: $CI_PROJECT_NAME
    paths:
      - .gradle/
    policy: pull-push
  only:
    - integration
    - staging
  tags:
    - backend
  when: manual