server:
  port: 9112
  shutdown: graceful

spring:
  application:
    name: scheduler-bill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:33060}/${DB_DATABASE:vika_dev}?characterEncoding=utf8&autoReconnect=true
    username: ${DB_USERNAME:vika}
    password: ${DB_PWD:password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

vikadata-starter:
  vika:
    enabled: true
    host: https://integration.vika.ltd
    # 维格表API 专用号 token
    token: uskM7PcEPftF4wh0Ni1
  job:
    register-address: http://job.vika.ltd
    port: 9092
    appname: bill-executor-develop
    logpath: logs/vikadata/job/bill-executor
    logretentiondays: 14
    access-token: onJvanLmSE3CqotjNp8hb7WRolpM1pdL