# 框架配置
spring:
  application:
    name: dingtalk-service
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:33060}/${DB_DATABASE:vika_dingtalk_dev}?characterEncoding=utf8&autoReconnect=true
    username: ${DB_USERNAME:root}
    password: ${DB_PWD:password}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 36000000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      auto-commit: true
      pool-name: DatebookHikariCP
  # Redis配置
  redis:
    # redis服务器主机，本地开发是公网地址，线上环境是内网地址
    host: ${REDIS_HOST:127.0.0.1}
    # redis服务器端口
    port: ${REDIS_PORT:6379}
    timeout: 30000
    # Redis连接池
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

# 自定义组件配置
vikadata-starter:
  # 组件：社交媒体集成方案
  social:
    dingtalk:
      enabled: true
      isv-corp-id: dingc7ad99cf1e0ad49a35c2f4657eb6378f
      corp-secret: mj3j3b15Gc3w6JPp46lvmM7lEXzavfZUEgUKsy72s3YZWRC7RkBTRTgKQ2mSfVWP
      suite-id: 7242002
      suite-key: suite88qw1yq0q48b4tez
      suite-secret: 6ITdgMwVcDYgnHT-IfG8_Szvc8-vMWBwwkCUjdlNaxWgGDFXQaYAsO_jhpyXdpg1
      vika-dst-id: dstctCRkFl5nYEbJSB
      corp-h5-app:
        app-key: dingpp0pil1snqypkjym
        app-secret: ZrVyKPrGkOeLMTmlDmFmcPK3eUIEDmABwT2DxuQONBOoTqZ0p1JEOedqxV_rNBo3
      mobile-app:
        app-id: dingoaumy4mh7oesecamid
        app-secret: A1-kYsquLtLr9e_XXnOAoMaqxEjC5xvMUeAztFxPy8YGgsYmeXsSu7QvwrmCcw1P
      isv-app-list:
        - suite-id: 20395001
          app-id: 87343
          suite-key: suitek31nyhjbb65itdvp
          suite-secret: TJqspsouY3vxJ3GNHrlr0xRUVIl3wuste8ERERtLetBuOJCfgY6ggj_vb0J4euwb
          aes-key: cha7KYiRod1bQINsHIJlQSqJlHC01LyuKa6S1iQBkIB
          token: Ivs5LO39ucfXPZfTd8cal1D66oHslG2C
          goods-code: DT_GOODS_881635221357061
          msg-tpl-id:
            welcome: 3f7cec2386f74f5c8aec1a48395abeb0
            comment: b4ac28623fd5493dbc5f995bb1cc17c7
            member: 5994e97c8766482bb971e6253ad7f6f1
  # 组件：在线API文档配置
  swagger:
    enabled: true

vikadata:
  social:
    const:
      vika-api:
        host: http://localhost:8081
        base-path: /api/v1

springfox:
  documentation:
    enabled: true

decorator:
  datasource:
    enabled: true
