# 框架配置
spring:
  application:
    name: dingtalk-service
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zew693k03e64948e.mysql.rds.aliyuncs.com:3306/dingtalk-test?characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: vika_developer
    password: develop@vikadata#189
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 36000000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      auto-commit: true
      pool-name: DatebookHikariCP
  # Redis配置
  redis:
    # redis服务器主机 内网地址
    host: r-2ze4ufmmfhtf7h5cog.redis.rds.aliyuncs.com
    password: develop@vikadata#189
    # redis服务器端口
    port: 6379
    timeout: 30000
    database: 3
    # Redis连接池
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

# 自定义组件配置
vikadata-starter:
  # 组件：社交媒体集成方案
  social:
    dingtalk:
      enabled: true
      isv-corp-id: dingc7ad99cf1e0ad49a35c2f4657eb6378f
      corp-secret: mj3j3b15Gc3w6JPp46lvmM7lEXzavfZUEgUKsy72s3YZWRC7RkBTRTgKQ2mSfVWP
      suite-id: 7242002
      suite-key: suite88qw1yq0q48b4tez
      suite-secret: 6ITdgMwVcDYgnHT-IfG8_Szvc8-vMWBwwkCUjdlNaxWgGDFXQaYAsO_jhpyXdpg1
      vika-dst-id: dstctCRkFl5nYEbJSB
      corp-h5-app:
        app-key: dingpp0pil1snqypkjym
        app-secret: ZrVyKPrGkOeLMTmlDmFmcPK3eUIEDmABwT2DxuQONBOoTqZ0p1JEOedqxV_rNBo3
      mobile-app:
        app-id: dingoaumy4mh7oesecamid
        app-secret: A1-kYsquLtLr9e_XXnOAoMaqxEjC5xvMUeAztFxPy8YGgsYmeXsSu7QvwrmCcw1P
      isv-app-list:
        - suite-id: 19716004
          app-id: 83994
          suite-key: suitevplzlcqgf0u0gkrt
          suite-secret: TUb9WbxSY6cdbjG16RoiN0j_XfgeDmcPP252cdZby3xz3-Dh3UcZp2LGre24nt1_
          aes-key: 3m5nw9gzejyi58xfw7qabouj40gc0xbm9wad60ednti
          token: nIHmhNlglsDLx6RMfxeviPT9essjpGPy
          msg-tpl-id:
            welcome: 048ff56310e548d782428e9a2f9abdc8
            comment: 699676fadabb45eba33aa81a21a00659
            member: 38288df5374840a6a9bb67fa50901ca5
  # 组件：在线API文档配置
  swagger:
    enabled: true

vikadata:
  social:
    const:
      vika-api:
        host: https://test.vika.ltd
        base-path: /api/v1

springfox:
  documentation:
    enabled: true

decorator:
  datasource:
    enabled: true

grpc:
  server:
    port: 9092