# 框架配置
spring:
  application:
    name: dingtalk-service
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zew693k03e64948e.mysql.rds.aliyuncs.com:3306/vikadata-dingtalk?characterEncoding=utf8&autoReconnect=true&useSSL=true
    username: vika_developer
    password: develop@vikadata#189
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 36000000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      auto-commit: true
      pool-name: DatebookHikariCP
  # Redis配置
  redis:
    # redis服务器主机 内网地址
    host: r-2ze4ufmmfhtf7h5cog.redis.rds.aliyuncs.com
    password: develop@vikadata#189
    # redis服务器端口
    port: 6379
    timeout: 30000
    database: 9
    # Redis连接池
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms

# 自定义组件配置
vikadata-starter:
  # 组件：社交媒体集成方案
  social:
    dingtalk:
      enabled: true
      isv-corp-id: dingc7ad99cf1e0ad49a35c2f4657eb6378f
      corp-secret: mj3j3b15Gc3w6JPp46lvmM7lEXzavfZUEgUKsy72s3YZWRC7RkBTRTgKQ2mSfVWP
      suite-id: 7242002
      suite-key: suite88qw1yq0q48b4tez
      suite-secret: 6ITdgMwVcDYgnHT-IfG8_Szvc8-vMWBwwkCUjdlNaxWgGDFXQaYAsO_jhpyXdpg1
      vika-dst-id: dstctCRkFl5nYEbJSB
      corp-h5-app:
        app-key: dingpp0pil1snqypkjym
        app-secret: ZrVyKPrGkOeLMTmlDmFmcPK3eUIEDmABwT2DxuQONBOoTqZ0p1JEOedqxV_rNBo3
      mobile-app:
        app-id: dingoaumy4mh7oesecamid
        app-secret: A1-kYsquLtLr9e_XXnOAoMaqxEjC5xvMUeAztFxPy8YGgsYmeXsSu7QvwrmCcw1P
      isv-app-list:
        - suite-id: 19704002
          app-id: 83919
          suite-key: suiteybkflwglluwcjnmv
          suite-secret: 8hSFeHren95_kgDzFvjWTu-zZG71c_O0YMBzoQuLVRwCKhsLgSRp3AuaBpwGmlhv
          aes-key: f3b8o5tq3c4lrzmr1p7agfzyzmj8cpg5egv2yp7uubq
          token: 6iyUG2vtOa45QjTKaGZCfhT3k1dW9DyF
          msg-tpl-id:
            welcome: 835b5468f44e44b2a47674599f92fc47
            comment: 8f41773b6eb54d6bba9d82392956dea1
            member: dc79d4fb0f554ff0af08af4c1f04caa6
  # 组件：在线API文档配置
  swagger:
    enabled: false
# 常量配置
vikadata:
  social:
    const:
      vika-api:
        host: https://vika.cn
        base-path: /api/v1
# grpc server 配置
grpc:
  server:
    port: 9092