space_scheduler_integration_docker:
  stage: docker
  image: vikadata/dind-java:latest
  services:
    - name: vikadata/dind-java:latest
      command: [ "--registry-mirror=https://nt14bg6k.mirror.aliyuncs.com" ]
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://vikadata__dind-java:2375"
    # 不需要拉取代码
    BUILD_ENV: integration
    VERSION_TYPE: alpha
    DOCKER_IMAGE_NAME: cargo.vikadata.com/system-tenant_integration/space-job-executor
    DOCKER_IMAGE_TAG: 0.13.3-$BUILD_ENV.$VERSION_TYPE.$CI_PIPELINE_ID
  # 缓存依赖
  cache:
    # 继承全局配置
    key: $CI_PROJECT_NAME
    paths:
      - .gradle/
    policy: pull-push
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew -v
    - ./gradlew build -D profile=$BUILD_ENV --build-cache -x test
    - cp -r vikadata-scheduler/scheduler-space/build/libs/scheduler-space.jar ./docker
    - echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> docker.env
    - echo "BUILD_ENV=$BUILD_ENV" >> docker.env
    - chmod a+x ./ci/script/build_docker.sh
    - sh ./ci/script/build_docker.sh
  artifacts:
    name: $CI_JOB_ID
    paths:
      - ci/script
    expire_in: 1 day
    reports:
      dotenv: docker.env
  only:
    refs:
      - integration
    changes:
      - vikadata-scheduler/scheduler-space/**/*
  tags:
    - backend

space_scheduler_integration_deploy:
  stage: deploy
  dependencies:
    - space_scheduler_integration_docker
  image: python:3.9.5
  variables:
    # 不需要拉取代码
    GIT_STRATEGY: none
    # 集群名称
    CLUSTER_NAME: compass-stack
    # 分区
    PARTITION: integration
    # 租户
    TENANT: system-tenant
    # 应用名称
    APP_NAME: space-job-executor
    # NAMESPACE
    NAMESPACE: integration
    # 跟EKS集群上的工作负载名称一致
    DEPLOY_NAME: space-job-executor-v1
    # 镜像名
    DOCKER_IMAGE_NAME: cargo.vikadata.com/system-tenant_integration/space-job-executor
  # 不需要缓存
  cache: { }
  script:
 #   - chmod a+x ./ci/script/deploy.sh
 #   - ./ci/script/deploy.sh
    - DEPLOY_SERVER="$DEPLOY_SERVER_INTEGRATION"
    - sh ./ci/script/deploy-eks.sh
  only:
    refs:
      - integration
    changes:
      - vikadata-scheduler/scheduler-space/**/*
  tags:
    - backend
